import LegacyPage from "@/components/LegacyPage";

export const metadata = {
  title: "Activités DIY – Toys\"R\"Us | AJBloks",
};

export default function Page() {
  return (
    <LegacyPage
      lang="fr"
      stylesheets={["/legacy/cart-drawer.css","/legacy/signup-drawer.css","/legacy/site-menu.css","/legacy/diy-shell.css","/legacy/diy-article-newsletter.css","/legacy/site-footer.css","/legacy/dashboard-fab.css","/legacy/responsive-shell.css","/legacy/site-header.css"]}
      inlineStyles={["\n  :root {\n    --tru-blue: #0057A8;\n    --tag-blue-bg: #D6EAF8;\n    --tag-blue-text: #1A6FA0;\n    --tag-purple-bg: #E8D5F5;\n    --tag-purple-text: #7B2D8B;\n    --tag-green-bg: #D5F5E3;\n    --tag-green-text: #1E8449;\n    --tag-red-bg: #FADBD8;\n    --tag-red-text: #C0392B;\n    --tag-orange-bg: #FDEBD0;\n    --tag-orange-text: #CA6F1E;\n  }\n\n  .page-hero { width: 100%; line-height: 0; overflow: hidden; }\n  .page-hero img { width: 100%; display: block; object-fit: cover; }\n\n  .breadcrumb {\n    background: rgb(249, 249, 249);\n    padding: 22px 18px;\n    font-size: 18px;\n    color: #1450c4;\n  }\n  .breadcrumb a { color: #1450c4; text-decoration: underline; font-weight: 500; }\n  .breadcrumb .sep { color: #1a1a1a; margin: 0 6px; text-decoration: none; }\n\n  .tagged-header {\n    padding: 24px 16px 28px;\n    text-align: center;\n    font-family: 'Buenos Aires', sans-serif;\n    font-size: 24px;\n    font-weight: 800;\n    line-height: 1.3;\n  }\n\n  .activity-cards { padding-top: 0; padding-bottom: 40px; }\n  .activity-card { padding: 0 16px 20px; }\n  .activity-card .card-link { display: block; color: inherit; text-decoration: none; }\n  .activity-card .card-link:hover h3 { color: var(--tru-blue); }\n\n  .tag {\n    display: inline-block;\n    font-family: 'Buenos Aires', sans-serif;\n    font-weight: 700;\n    font-size: 14px;\n    padding: 10px 18px;\n    border-radius: 999px;\n    text-decoration: none;\n    transition: transform .08s;\n  }\n  .tag:active { transform: translateY(2px); box-shadow: none !important; }\n  .tag.blue  { background: var(--tag-blue-bg); color: var(--tag-blue-text); box-shadow: 0 3px 0 var(--tag-blue-text); }\n  .tag.purple{ background: var(--tag-purple-bg); color: var(--tag-purple-text); box-shadow: 0 3px 0 var(--tag-purple-text); }\n  .tag.green { background: var(--tag-green-bg); color: var(--tag-green-text); box-shadow: 0 3px 0 var(--tag-green-text); }\n  .tag.red   { background: var(--tag-red-bg); color: var(--tag-red-text); box-shadow: 0 3px 0 var(--tag-red-text); }\n  .tag.orange{ background: var(--tag-orange-bg); color: var(--tag-orange-text); box-shadow: 0 3px 0 var(--tag-orange-text); }\n\n  .activity-card .card-img {\n    border-radius: 14px;\n    overflow: hidden;\n    height: 200px;\n    background: #dde8d8;\n    margin-bottom: 12px;\n  }\n  .activity-card h3 { font-size: 20px; font-weight: 800; margin-bottom: 6px; }\n  .activity-card p { font-size: 14px; color: #444; line-height: 1.5; margin-bottom: 10px; }\n  .activity-card .card-tags { display: flex; gap: 8px; flex-wrap: wrap; }\n  .img-placeholder {\n    width: 100%; height: 100%;\n    display: flex; align-items: center; justify-content: center;\n    color: #888; font-size: 13px; background: #f0f4f8;\n    padding: 16px; text-align: center;\n  }\n\n  .empty-state {\n    padding: 24px 16px 40px;\n    text-align: center;\n    color: #666;\n    font-size: 16px;\n  }\n"]}
      bodyHtml={"\n\n<div class=\"diy-content\">\n  <section class=\"page-hero\">\n    <img src=\"https://res.cloudinary.com/dbtkfjrvd/image/upload/v1782383899/Design_sans_titre_44_rkv5bi.png\" alt=\"Activités créatives\">\n  </section>\n\n  <nav class=\"breadcrumb\">\n    <a href=\"/\">Accueil</a><span class=\"sep\">›</span><a href=\"/toysrus-diy-activities\">Activités DIY</a><span class=\"sep\">›</span><span id=\"breadcrumbTag\">Bike</span>\n  </nav>\n\n  <h1 class=\"tagged-header\" id=\"taggedHeader\">Tagged with:</h1>\n\n  <div class=\"activity-cards\" id=\"activityCards\"></div>\n  <p class=\"empty-state\" id=\"emptyWilaya\" hidden=\"\">Non activities found pour this tag yet.</p>\n\n  <section class=\"diy-listing-newsletter article-newsletter\" aria-label=\"Infolettre signup\">\n    <h2>S'inscrire pour Fun!</h2>\n    <p class=\"diy-listing-newsletter-intro article-newsletter-intro\">Recevez des nouvelles exclusives sur les jouets, des idées de jeu et des avis !</p>\n    <form id=\"listing-signup-form\">\n      <div class=\"signup-row\">\n        <input type=\"email\" id=\"listing-email-input\" placeholder=\"Entrez votre e-mail\" required=\"\" aria-label=\"Adresse e-mail\">\n        <button type=\"submit\">S'inscrire</button>\n      </div>\n      <p class=\"signup-disclaimer\">En vous inscrivant à notre infolettre, vous acceptez nos <a href=\"/toysrus-conditions\">conditions d'utilisation</a> et notre <a href=\"/toysrus-privacy\">politique de confidentialité</a>.</p>\n      <p class=\"signup-confirm\" id=\"listing-signup-confirm\" role=\"status\"></p>\n    </form>\n  </section>\n</div>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"}
      externalScripts={["/legacy/api-client.js","/legacy/diy-activities-data.js","/legacy/diy-activities-ui.js","/legacy/site-menu.js","/legacy/dashboard-fab.js","/legacy/site-footer.js","/legacy/cart-drawer.js","/legacy/site-header.js","/legacy/diy-shell.js","/legacy/signup-drawer.js","/legacy/auth-links.js"]}
      inlineScripts={[]}
    />
  );
}
