import LegacyPage from "@/components/LegacyPage";

export const metadata = {
  title: "Livraison – Toys\"R\"Us | AJBloks",
};

export default function Page() {
  return (
    <LegacyPage
      lang="fr"
      stylesheets={["/legacy/cart-drawer.css","/legacy/signup-drawer.css","/legacy/site-menu.css","/legacy/diy-shell.css","/legacy/site-footer.css","/legacy/dashboard-fab.css","/legacy/responsive-shell.css","/legacy/site-header.css"]}
      inlineStyles={["\n  @import url(https://db.onlinewebfonts.com/c/1b62cb414d23538e8a465e7f50aa7932?family=Buenos+Aires);\n\n  .diy-content {\n    background: #fff;\n    min-height: calc(100vh - 120px);\n    min-height: calc(100dvh - 120px);\n  }\n\n  .livraison-main {\n    width: 100%;\n    background: #fff;\n    padding: 28px 20px 48px;\n    font-family: 'Buenos Aires', sans-serif;\n    color: #11214A;\n  }\n\n  .livraison-title1 {\n    font-size: clamp(2rem, 6vw, 2.5rem);\n    font-weight: 800;\n    margin: 0 0 20px;\n    line-height: 1.15;\n  }\n\n  .livraison-title2 {\n    font-size: clamp(1.35rem, 4vw, 1.75rem);\n    font-weight: 700;\n    margin: 0 0 18px;\n    line-height: 1.25;\n  }\n\n  .livraison-text {\n    width: 380px;\n    max-width: 100%;\n    font-size: 0.875rem;\n    line-height: 1.6;\n    margin: 0 0 14px;\n    color: #1a1a1a;\n  }\n\n  .livraison-text-2 {\n    list-style-type: circle;\n    padding-left: 1.35em;\n  }\n\n  .livraison-text-2 li {\n    line-height: 1.6;\n  }\n\n  .livraison-table-wrap {\n    margin-top: 22px;\n    overflow-x: auto;\n  }\n\n  .livraison-table-wrap + .livraison-text {\n    margin-top: 22px;\n  }\n\n  .table-bordered {\n    width: 385px;\n    max-width: 100%;\n    border-collapse: collapse;\n    border: 1px solid #000;\n    table-layout: fixed;\n    font-size: 0.95rem;\n  }\n\n  .table-bordered th,\n  .table-bordered td {\n    border: 1px solid #000;\n    padding: 14px 12px;\n    text-align: left;\n    vertical-align: middle;\n  }\n\n  .table-bordered thead th {\n    background: #004ebc;\n    color: #fff;\n    font-weight: 700;\n  }\n\n  .table-bordered tbody tr {\n    background: #fff;\n  }\n"]}
      bodyHtml={"\n\n<div class=\"diy-content\">\n  <section class=\"livraison-main\" aria-label=\"Livraison\">\n    <h1 class=\"livraison-title1\">Livraison</h1>\n    <h2 class=\"livraison-title2\">Informations sur la livraison AJBLOKS</h2>\n    <p class=\"livraison-text\">AJBLOKS propose actuellement la livraison standard.</p>\n    <ul class=\"livraison-text livraison-text-2\">\n      <li>Les frais et les délais de livraison standard sont indiqués ci-dessous :</li>\n    </ul>\n\n    <div class=\"livraison-table-wrap\">\n      <table class=\"table-bordered\">\n        <thead>\n          <tr>\n            <th scope=\"col\">Mode de livraison</th>\n            <th scope=\"col\">Coût</th>\n            <th scope=\"col\">Délai de livraison</th>\n          </tr>\n        </thead>\n        <tbody>\n          <tr>\n            <td>Livraison standard</td>\n            <td>Gratuite pour les commandes supérieures à 6 500 DZD</td>\n            <td>2 à 5 jours ouvrables</td>\n          </tr>\n          <tr>\n            <td>Livraison standard</td>\n            <td>Tarif fixe pour les commandes inférieures à 6 500 DZD. Les tarifs varient selon la société de livraison partenaire et la wilaya de destination (de 350 à 1 200 DZD).</td>\n            <td>2 à 5 jours ouvrables</td>\n          </tr>\n          <tr>\n            <td>Livraison standard (communes sélectionnées d'Alger-Centre)</td>\n            <td>Gratuite pour les communes de Birtouta, Douéra, Baraki, Sidi Moussa, Khraïcia et Ouled Chebel</td>\n            <td>1 à 3 jours ouvrables</td>\n          </tr>\n        </tbody>\n      </table>\n    </div>\n\n    <p class=\"livraison-text\">Les commandes sont traitées et expédiées dans un délai de 1 à 2 jours ouvrables après la confirmation du paiement.</p>\n\n    <div class=\"livraison-table-wrap\">\n      <table class=\"table-bordered\">\n        <thead>\n          <tr>\n            <th scope=\"col\">Mode de livraison</th>\n            <th scope=\"col\">Coût</th>\n            <th scope=\"col\">Délai de livraison</th>\n          </tr>\n        </thead>\n        <tbody>\n          <tr>\n            <td>Livraison express</td>\n            <td>Des frais additionnels s'appliquent (entre 500 et 1 500 DZD)</td>\n            <td>1 à 3 jours ouvrables</td>\n          </tr>\n          <tr>\n            <td>Retrait en magasin</td>\n            <td>Gratuit</td>\n            <td>Prêt sous 24 heures</td>\n          </tr>\n        </tbody>\n      </table>\n    </div>\n  </section>\n</div>\n\n\n\n\n\n\n\n\n\n\n\n"}
      externalScripts={["/legacy/site-menu.js","/legacy/dashboard-fab.js","/legacy/site-footer.js","/legacy/cart-drawer.js","/legacy/site-header.js","/legacy/diy-shell.js","/legacy/signup-drawer.js","/legacy/auth-links.js"]}
      inlineScripts={[]}
    />
  );
}
